"""A file simply containing the biggest variables here. Y'know, tables n' stuff."""

skin_colors = [
    "Pale",
    "Light",
    "Brown",
    "Dark Brown",
    "Fancy (Use fur colors)", # 4
]

SKIN_COLORS_MAX = 4

SKIN_COLORS_STANDMAX = 3

species = [
    "Robot", # 0, gen again
    "Angel", # 1, gen again
    "Demon", # 2, gen again
    "Human", # 3
    "Hybrid", # 4, gen again twice
    "Cat",
    "Fox",
    "Bear",
    "Snake",
    "Skunk",
    "Squirrel",
    "Wolf",
    "Shark",
    "Turtle",
    "Protogen",
    "Deer",
    "Dog",
    "Bee",
    "Frog",
    "Dolphin",
    "Sheep",
    "Goat",
    "Dragon",
    "Raccoon",
    "Ringtail",
    "Mongoose",
    "Hyena",
    "Axolotl",
    "Bat",
    "Bunny",
    "Octopus",
    "Mouse",
    "Hamster",
    "Pigeon",
    "Spider",
    "Possum",
    "Kobold",
    "Cow",
    "Leopard",
    "Moth",
    "Fish",
    "Owl",
    "Elf",
]

SPECIES_MAX = 42

fur_colors = [
    "Red",
    "Blue",
    "Light Blue",
    "Cyan",
    "Black",
    "Purple",
    "Pink",
    "Orange",
    "Yellow",
    "Light Purple",
    "Gray",
    "Light Gray",
    "Light Brown",
    "Light Red",
    "Brown",
    "Green",
    "White",
    "Galaxy",
    "Multi-Tone (Generate again twice)", # 18
]

FUR_COLORS_MAX = 18

FUR_COLORS_MAXLESS = 17

natural_hair_colors = [
    "Black",
    "Dark Brown",
    "Brown",
    "Blonde",
    "White",
    "Gray",
    "Ginger",
]

NATURAL_HAIR_COLORS_MAX = 6

hair_styles = [
    'Shoulder-Length',
    'Neck-Length',
    'Short',
    'Ponytail',
    'Waist-Length',
    'Long',
]

HAIR_STYLES_MAX = 5

sexualities = [
    "Heterosexual",
    "Bisexual",
    "Homosexual",
    "Asexual",
    "Pansexual",
]

SEXUALITIES_MAX = 4

genders = [
    "Female",
    "Male",
    "Androgynous", # love this one, lmao
]

GENDER_MAX = 2

gender_suffixes = [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Trans",
    "Non-Binary",
]

GENDER_SUFFIX_MAX = 9

eye_colors = [
    "Blue",
    "Red",
    "Pink",
    "Purple",
    "Green",
    "Brown",
    "Orange",
    "Yellow",
    "Black",
    "White",
    "Gray",
    "Galaxy",
    "Heterochromic (Generate again twice)", # 12
]

EYE_COLORS_MAX = 12

nationalities = [
    "Irish",
    "British",
    "American",
    "Canadian",
    "Mexican",
    "Russian",
    "German",
]

NATIONALITIES_MAX = 6

hats = [
    "Beanie",
    "Baseball Cap",
    "Cowboy Hat",
    "Space Helmet",
    "None",
    "Bow",
    "Hoodie Hood",
]

HAT_MAX = 7

cloth_sizes = [
    "Large",
    "Medium",
    "Small",
]

SIZE_MAX = 2

hat_colors = [
    "Red",
    "Blue",
    "Light Blue",
    "Cyan",
    "Black",
    "Purple",
    "Pink",
    "Orange",
    "Yellow",
    "Light Purple",
    "Gray",
    "Light Gray",
    "Light Brown",
    "Light Red",
    "Green",
    "Brown",
    "White",
]

HAT_COLOR_MAX = 16

tops = [
    "Hoodie",
    "T-Shirt",
    "Dress Shirt",
    "Polo Shirt",
    "Dress",
    "Sweater",
    "Tank Top",
]

TOP_MAX = 6

out_tops = [
    "Suit Jacket",
    "Jacket",
    "Trench Coat",
    "none",
    "none",
    "none",
    "none",
]

OUT_TOP_MAX = 6

top_colors = [
    "Red",
    "Blue",
    "Light Blue",
    "Cyan",
    "Black",
    "Purple",
    "Pink",
    "Orange",
    "Yellow",
    "Light Purple",
    "Gray",
    "Light Gray",
    "Light Brown",
    "Light Red",
    "Brown",
    "Green",
    "White",
    "Galaxy",
    "Multi-Tone (Generate again twice)", # 18
]

TOP_COLOR_MAX = 18

bottoms = [
    "Pants",
    "Jeans",
    "Shorts",
    "Skirt",
]

BOTTOM_MAX = 3

socks = [
    "Thigh-Highs",
    "Knee-Length Socks",
    "Socks"
]

SOCKS_MAX = 2

bottom_colors = [
    "Red",
    "Blue",
    "Light Blue",
    "Cyan",
    "Black",
    "Purple",
    "Pink",
    "Orange",
    "Yellow",
    "Light Purple",
    "Gray",
    "Green",
    "Light Gray",
    "Light Brown",
    "Light Red",
    "Brown",
    "White",
]

BOTTOM_COLOR_MAX = 16

shoes = [
    "Shoes",
    "Sneakers",
    "Boots",
    "Sandals",
    "Heels",
]

SHOE_MAX = 4

shoe_colors = [
    "Red",
    "Blue",
    "Light Blue",
    "Cyan",
    "Black",
    "Purple",
    "Pink",
    "Green",
    "Orange",
    "Yellow",
    "Light Purple",
    "Gray",
    "Light Gray",
    "Light Brown",
    "Light Red",
    "Brown",
    "White",
]

SHOE_COLOR_MAX = 16

masc_names = [
    "Nick",
    "Harry",
    "Robert",
    "Mark",
    "Sean",
    "Shaun",
    "Shawn",
    "Andre",
    "Billy",
    "Carl",
    "Carlos",
    "Charles",
    "Cody",
    "Corey",
    "Cosmo",
    "Cyrus",
    "Dave",
    "Dean",
    "Derek",
    "Dom",
    "Eddie",
    "Elijah",
    "Felix",
    "Finn",
    "Fred",
    "George",
    "Gary",
    "Isaac",
    "Jaden",
    "Jamie",
    "James",
    "Jay",
    "Joel",
    "John",
    "Juan",
    "Jude",
    "Julian",
    "Kevin",
    "Lee",
    "Leon",
    "Leo",
    "Luis",
    "Lukas",
    "Marc",
    "Martin",
    "Matt",
    "Max",
    "Mick",
    "Monty",
    "Nolan",
    "Orion",
    "Owen",
    "Parker",
    "Perry",
    "Pete",
    "Ralph",
    "Ray",
    "Ronald",
    "Skip",
    "Sonny",
    "Stephen",
    "Steve",
    "Theo",
    "Toby",
    "Tom",
    "Tyler",
    "Vincent",
    "Wes",
    "Wesley",
    "William",
    "Zac",
    "Alex",
    "Shay",
    "Frankie",
    "Angel",
    "Jude",
    "Reed",
    "Remi",
    "Robin",
    "Quinn",
    "Bailey",
    "Ash",
    "Charlie",
    "Jesse",
    "Phoenix",
    'Aaron',
    'Adam',
    'Andrew',
    'Andy',
    'Brian',
    'Bill',
    'Bob',
    'Bruce',
    'Brandon',
    'Chris',
    'Craig',
    'Dirk',
    'Drew',
    'Dan',
    'Damien',
    'Doug',
    'Edward',
    'Edgar',
    'Frank',
    'Grant',
    'Gil',
    'Greg',
    'Hank',
    'Harold',
    'Ian',
    'Jack',
    'Jones',
    'Kim',
    'Keith',
    'Leonard',
    'Leland',
    'Lyle',
    'Mitch',
    'Mitchell',
    'Miles',
    'Oscar',
    'Otto',
    'Oliver',
    'Peter',
    'Phil',
    'Phillip',
    'Patrick',
    'Quentin',
    'Raymond',
    'Richard',
    'Rollo',
    'Rick',
    'Ryan',
    'Trent',
    'Trevor',
    'Tommy',
    'Thomas',
    'Victor',
    'Vince',
    'Wilson',
    'Will',
    'Xavier',
    'Zach',
    'Zachary',
]

MASC_NAMES_MAX = 143

fem_names = [
    "Abi",
    "Addison",
    "Alexis",
    "Alice",
    "Annie",
    "Ashley",
    "Astra",
    "Bee",
    "Betty",
    "Blair",
    "Carina",
    "Carla",
    "Carmen",
    "Cassie",
    "Celeste",
    "Cindy",
    "Daisy",
    "Daphne",
    "Dawn",
    "Delia",
    "Elaine",
    "Elara",
    "Ellen",
    "Emilia",
    "Emma",
    "Eva",
    "Evelyn",
    "Evie",
    "Hayley",
    "Hilda",
    "Iris",
    "Isabelle",
    "Isabella",
    "Jessie",
    "Jodi",
    "June",
    "Kelly",
    "Laurie",
    "Layla",
    "Lili",
    "Linda",
    "Lonnie",
    "Lucy",
    "Luna",
    "Lyra",
    "Marie",
    "Maya",
    "Melinda",
    "Mila",
    "Mimi",
    "Mina",
    "Mira",
    "Misty",
    "Molly",
    "Montana",
    "Nona",
    "Rosa",
    "Rosie",
    "Sara",
    "Shelby",
    "Skylar",
    "Sunny",
    "Sydney",
    "Star",
    "Stormy",
    "Taylor",
    "Vera",
    "Vivi",
    "Vivian",
    "Wanda",
    "Wendy",
    "Zoe",
    "Charlotte",
    "Cosma",
    "Alex",
    "Shay",
    "Angel",
    "Demi",
    "Morgan",
    "Robin",
    "Sky",
    "Quinn",
    "Bailey",
    "Ash",
    "Charlie",
    "Jesse",
    "Kit",
    "Payton",
    "Phoenix",
    "Bonnie",
    "Yvonne",
    "Amanda",
    "Abigail",
    "Helen",
    "Amy",
    "Tammy",
    "Bridgette",
    "Danielle",
    "Erica",
    "Eri",
    "Jade",
    "Jane",
    "Margaret",
    "Dahlia",
    "Norine",
    "Nori",
]

FEM_NAMES_MAX = 105

andro_names = [
    "Alex",
    "Shay",
    "Frankie",
    "Angel",
    "Morgan",
    "Reed",
    "Remi",
    "Robin",
    "Sky",
    "Quinn",
    "Bailey",
    "Ash",
    "Charlie",
    "Jesse",
    "Kit",
    "Phoenix",
    "Jamie",
    "Jules",
    "Kris",
]

ANDRO_NAMES_MAX = 18 # Some of these were pulled from the other name tables, none of them were added recently

last_names = [
    "Astra",
    "Bailey",
    "Benika",
    "Bee",
    "Carina",
    "Canela",
    "Chiara",
    "Dawn",
    "Elaine",
    "Emilia",
    "Emma",
    "Frankie",
    "Fuffi",
    "Jantine",
    "June",
    "Karin",
    "Kata",
    "Kelly",
    "Kelsey",
    "Laurie",
    "Lenna",
    "Lindsay",
    "Linn",
    "Lorene",
    "Lorette",
    "Lucy",
    "Luna",
    "Lyra",
    "Malina",
    "Marie",
    "Margo",
    "Mira",
    "Montana",
    "Morgan",
    "Nalani",
    "Paris",
    "Peony",
    "Quinn",
    "Robin",
    "Saige",
    "Samara",
    "Scout",
    "Shana",
    "Shay",
    "Sigrun",
    "Star",
    "Tania",
    "Taylor",
    "Zaray",
    "Zuray",
    "Ziv",
    "Zlata",
    "Zora",
    "Oswin",
    "William",
    "Stelian",
    "Melville",
    "Sterling",
    "Zoran",
    "Brayn",
    "Candrés",
    "Elynzo",
    "Francis",
    "Irving",
    "Julian",
    "Keane",
    "Kenteu",
    "Moritz",
    "Monty",
    "Orion",
    "Parker",
    "Paco",
    "Prince",
    "Sherman",
    "Skipper",
    "Yannick",
    "Isym",
    "Carpenter",
]

LAST_NAMES_MAX = 77

abilities = [
    'Has a human disguise',
    'Can store items in a \"pocket dimension\"',
    'Can travel between universes',
    'Can come back to life upon death',
    'Can take a LOT of damage before dying',
    'Can legally fly a plane',
    'Can control electricity',
    'Has inhuman reaction time',
    'Can shapeshift',
    'Can resize any object',
    'Can travel by using electronic devices',
    'Can go back to set points in time by using photos or videos',
    'Knows details about other timelines',
    'Can break the fourth wall',
    'Can calm people down very easily',
    'Can sing loud enough to cause physical damage',
    'Has clothes that are unable to catch on fire',
    'Is unable to be harmed by fire',
    'Can control fire',
    'Can visualize an object\'s past',
    'Can build an internal \"profile\" of an object\'s details',
    'Can turn anything to ash',
    'Doesn\'t age but isn\'t immortal',
    'Can view a top-down view of any area',
    'Can create fireballs (wouldn\'t this just be fire control?)',
    'Can create an orb allowing them to view any target or time',
    'Can slow time',
    'Can teleport',
    'Can possess living beings',
    'Can see people and objects through walls',
    'Can control wind',
    'Has telekinesis',
    'Is a divine being',
    'Can always say the right thing to a person',
    'Is able to sneak around easier than most',
]

ABILITY_MAX = 34

skills_landd = [
    'Cooking',
    'Charisma',
    'Handiness',
    'Fitness',
    'Logic',
    'Creativity',
    'Cleaning',
    'Painting',
    'Guitar',
    'Fishing',
    'Writing',
    'Gardening',
    'Pottery',
    'Photography',
    'Alcohol Brewing',
    'Martial Arts',
    'Sculpting',
    'Inventing',
    'Tattooing',
    'Mixology',
    'Drums',
    'Piano',
    'Bass',
    'Hunting',
    'Gambling',
    'Alchemy',
    'Science',
    'Social Networking',
    'Street Art',
    'Violin',
    'Dancing',
    'Scuba Diving',
    'Future Technology',
    'Robotics',
    'Artisan',
    'Comedy',
    'Gourmet Cooking',
    'Mischief',
    'Programming',
    'Rocket Science',
    'Video Gaming',
    'Herbalism',
    'Baking',
    'Wellness',
    'DJ Mixing',
    'Singing',
    'Pipe Organ',
    'Bowling',
    'Parenting',
    'Veterinarian',
    'Pet Training',
    'Archaeology',
    'Flower Arranging',
    'Acting',
    'Media Production',
    'Research & Debate',
    'Fabrication',
    'Knitting',
    'Rock Climbing',
    'Skiing',
    'Snowboarding',
    'Medium',
    'Cross-Stitching',
    'Entrepreneur',
    'Gemology',
    'Meditation',
    'Yoga',
    'Skating',
]

SKILL_MAX = 67

colors_landd = [ 
    'Azure',
    'Blue',
    'Navy Blue',
    'Wheat',
    'Yellow',
    'Golden',
    'Orange',
    'Coral',
    'White',
    'Silver',
    'Gray',
    'Charcoal',
    'Black',
    'Brown',
    'Khaki',
    'Red',
    'Crimson',
    'Maroon',
    'Fuchsia',
    'Hot Pink',
    'Magenta',
    'Purple',
    'Indigo',
    'Cyan',
    'Teal',
    'Green',
    'Emerald',
]

COLORS_MAX = 26

personality_traits = [
    'Friendly',
    'Chill',
    'Upbeat',
    'Optimistic',
    'Shy',
    'Timid',
    'Cheerful',
    'Curious',
    'Serious',
    'Calm',
    'Dangerous',
]

PERSONALITY_MAX = 10